<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.aocdev</groupId>
        <artifactId>jdocusaurus</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>jdocusaurus-test</artifactId>
    <packaging>jar</packaging>

    <name>JDocusaurus Test</name>
    <description>Modulo de test para verificar la generacion de documentacion</description>

    <dependencies>
        <dependency>
            <groupId>org.aocdev</groupId>
            <artifactId>jdocusaurus-annotations</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.aocdev</groupId>
            <artifactId>jdocusaurus-processor</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
