package org.aocdev.jdocusaurus.processor.generator;

import org.aocdev.jdocusaurus.processor.config.JDocusaurusConfig;
import org.aocdev.jdocusaurus.processor.model.*;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

public class SidebarGenerator implements Generator {

    private final JDocusaurusConfig config;

    public SidebarGenerator(JDocusaurusConfig config) {
        this.config = config;
    }

    @Override
    public void generate(ProjectModel model, DocWriter writer) throws IOException {
        if (!config.isFullStructure()) return;

        writer.write("sidebars.js", generateSidebar(model));
    }

    private String generateSidebar(ProjectModel model) {
        // When absolute path, docs are at root => no prefix needed for sidebar IDs
        // When relative path, files are under outputDir => use it as prefix
        String prefix = Path.of(config.getOutputDir()).isAbsolute()
                ? "" : config.getOutputDir() + "/";

        StringBuilder js = new StringBuilder();

        js.append("// Auto-generated by JDocusaurus\n");
        js.append("module.exports = {\n");
        js.append("  docs: [\n");

        // Overview
        js.append("    { type: 'doc', id: '").append(prefix).append("index', label: 'Overview' },\n");

        // API category
        if (!model.getClasses().isEmpty()) {
            js.append("    {\n");
            js.append("      type: 'category',\n");
            js.append("      label: 'API',\n");
            js.append("      items: [\n");
            js.append("        '").append(prefix).append("api/index',\n");
            for (ClassModel classModel : model.getClasses()) {
                js.append("        '").append(prefix).append("api/")
                        .append(toKebabCase(classModel.getClassName())).append("',\n");
            }
            js.append("      ],\n");
            js.append("    },\n");
        }

        // Flows category
        if (!model.getAllFlows().isEmpty()) {
            js.append("    {\n");
            js.append("      type: 'category',\n");
            js.append("      label: 'Flujos',\n");
            js.append("      items: [\n");
            js.append("        '").append(prefix).append("flows/index',\n");
            for (FlowModel flow : model.getAllFlows()) {
                js.append("        '").append(prefix).append("flows/")
                        .append(toKebabCase(flow.getName())).append("',\n");
            }
            js.append("      ],\n");
            js.append("    },\n");
        }

        // Data model category
        if (!model.getEntities().isEmpty()) {
            js.append("    {\n");
            js.append("      type: 'category',\n");
            js.append("      label: 'Modelo de Datos',\n");
            js.append("      items: [\n");
            js.append("        '").append(prefix).append("data-model/index',\n");
            for (EntityModel entity : model.getEntities()) {
                js.append("        '").append(prefix).append("data-model/")
                        .append(toKebabCase(entity.getClassName())).append("',\n");
            }
            js.append("      ],\n");
            js.append("    },\n");
        }

        // Events category
        if (!model.getEvents().isEmpty()) {
            js.append("    {\n");
            js.append("      type: 'category',\n");
            js.append("      label: 'Eventos',\n");
            js.append("      items: [\n");
            js.append("        '").append(prefix).append("events/index',\n");
            for (EventModel event : model.getEvents()) {
                js.append("        '").append(prefix).append("events/")
                        .append(toKebabCase(event.getDisplayName())).append("',\n");
            }
            js.append("      ],\n");
            js.append("    },\n");
        }

        // Business Rules
        if (!model.getBusinessRules().isEmpty()) {
            js.append("    { type: 'doc', id: '").append(prefix)
                    .append("business-rules/index', label: 'Reglas de Negocio' },\n");
        }

        // Integrations
        if (!model.getExternalServices().isEmpty()) {
            js.append("    { type: 'doc', id: '").append(prefix)
                    .append("integrations/index', label: 'Integraciones' },\n");
        }

        // Config
        if (!model.getConfigs().isEmpty()) {
            js.append("    { type: 'doc', id: '").append(prefix)
                    .append("config/index', label: 'Configuracion' },\n");
        }

        js.append("  ],\n");
        js.append("};\n");

        return js.toString();
    }

    private String toKebabCase(String name) {
        return name.replaceAll("([a-z])([A-Z])", "$1-$2")
                .replaceAll("[\\s_]+", "-")
                .toLowerCase();
    }
}
